 function [h,Lres,Lbeta] = evim_smooth(A,dzdt,mask,dx,a,surf_terrain,hmax,hlow,u,v)

%[h,Lres,Lbeta] = evim_smooth(A,dzdt,mask,dx,a,surf_terrain,hmax,hlow,u,v)

% Solving linear equation systems Ah=b based on CVX.

% A = matrix generated by evim_A.m from surface velocity field
% dzdt = array of vertical deformation
% mask = array of 1s and 0s denoting active landslide pixels
% dx = pixel spacing (e.g. InSAR geocoded results) 
% a = filtering parameter, alpha
% surf_terrain = surface elevation (a.l.s. m)
% hmax,hlow = Upper and lower boundaries for landslide thickness
% u,v = horizontal deformation, u:west-east, v: north-south

%h = estimated thickness
%Lres = misfit norm for plotting an Lcurve (||A*h - b||)
%Lbeta = smoothness norm for plotting an Lcurve (||B*h||)
%
%Copyright (C) 2025 Ya Kang, [kangya@njupt.edu.cn].
%
%-------------------------------------------------------------------------%
%This program is free software: you can redistribute it and/or modify
%it under the terms of the GNU General Public License as published by
%the Free Software Foundation
%
%This program is distributed in the hope that it will be useful,
%but WITHOUT ANY WARRANTY; without even the implied warranty of
%MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License
%along with this program.  If not, see <http://www.gnu.org/licenses/>.
%-------------------------------------------------------------------------%

[nrows,ncols] = size(dzdt);
len = nrows*ncols;
% dzdt = reshape(dzdt,len,1);
% dzdt(isnan(dzdt)) = 0;
mask = reshape(mask,len,1);

% Create smoothing matrix,
[B] = diff2D_evim_diag(nrows,ncols);   
% Create constant terms (b) for equations,
[FX,FY]=gradient(surf_terrain,dx); 
tmp=dzdt-FX.*u+FY.*v; %%  
tmp = reshape(tmp,len,1);
tmp(isnan(tmp)) = 0;
b = 2*dx*tmp;

%Invert for h with non-negative constraints,
lb = hlow*ones(len,1);                  %h >= 0 everywhere
ub = 0.0001+hmax*mask ;              %h < hlow in stable terrain only
%Solve using cvx,
cvx_begin
    variable h(len)
    minimize( norm(A*h-b) + a*norm(B*h) );
    subject to 
        lb <= h <= ub   
cvx_end

% Calculate norms for generating an L-curve,
Lres = norm(A*h - b);
Lbeta = norm(B*h);
%Reshape h to matrix,
h = reshape(h,nrows,ncols);
